import { Footer } from '@/components/Footer'
import { cn } from '@/lib/utils'
import { SiteHeader } from '@/modules/navigation/site-header'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const font = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: './favicon.ico' },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('font-sans antialiased', font.variable)}>
      <body className="min-h-screen dark:bg-slate-900 dark:text-slate-100">
        <Providers>
          <SiteHeader />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
